-- 테이블을 세로로 통합하기
/*
    select문 + UNION ALL + select문
*/
-- 테이블 통합시, 일치하지 않는 컬럼 병합하기
/*
    `NULL AS 알리아스`
*/
SELECT 
    TO_CHAR(SALES_DATE,'YYYY-MM-DD') SALES_DATE,
    PRODUCT_ID,
    NVL(USER_ID,NULL) USER_ID,
    SALES_AMOUNT
FROM 
(SELECT
    SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM ONlINE_SALE
WHERE TO_CHAR(SALES_DATE,'YYYY-MM') = '2022-03'

UNION ALL

SELECT
    SALES_DATE,PRODUCT_ID,NULL AS USER_ID,SALES_AMOUNT
FROM OFFLINE_SALE
WHERE TO_CHAR(SALES_DATE,'YYYY-MM') = '2022-03') un
ORDER BY un.SALES_DATE, un.PRODUCT_ID, un.USER_ID
