-- 코드를 입력하세요
SELECT
    ri.REST_ID,REST_NAME,FOOD_TYPE,FAVORITES,ADDRESS,
    rr.rs SCORE
FROM REST_INFO ri
JOIN (SELECT
        ROUND(AVG(REVIEW_SCORE),2) rs,REST_ID
     FROM REST_REVIEW
     GROUP BY REST_ID
    ) rr
ON (ri.REST_ID = rr.REST_ID)
WHERE ADDRESS LIKE '서울%'
ORDER BY SCORE DESC,FAVORITES DESC