SELECT
    A.FLAVOR AS FLAVOR
FROM(
    SELECT
        F.FLAVOR,
        SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) AS SUM
    FROM FIRST_HALF F
    JOIN JULY J ON (F.FLAVOR = J.FLAVOR)
    GROUP BY F.FLAVOR
    ORDER BY SUM DESC
) A
WHERE ROWNUM <= 3